//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teacher
    {
        public int ID { get; set; }
        public int TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string Subject { get; set; }
        public string Department { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
        public int Phone { get; set; }
        public int DateOfJoin { get; set; }
    }
}
